#!/bin/sh

echo "AR Wrapping $@"

while [ $# -gt 0 ]; do
	case $1 in
	*.lib|*.a)
		LINK_TARGET=`cygpath -w $1`
		;;
	*obj|*.o)
		OBJS="$OBJS `cygpath -w $1`"
		;;
	-*)
		ARGS="$ARGS $1"
		;;
	*)
		echo "Ignoring AR flag: $1"
		;;
	esac
	shift
done

if [ "$LINK_TARGET" = "" ]; then
	echo "Failed to extract target"
	exit 1
fi

echo "Target: $LINK_TARGET"
echo "Args: $ARGS"
echo "Objs: $OBJS"

#MSVCRTDIR="-LIBPATH:`cygpath -w '/c/Program Files (x86)/Microsoft Visual Studio 11.0/VC/WPSDK/WP80/lib/arm'`"
#echo lib -nologo -OUT:$LINK_TARGET $ARGS $OBJS
lib -nologo -OUT:$LINK_TARGET $ARGS $OBJS # -NODEFAULTLIB:msvcrt msvcrt.lib $MSVCRTDIR
exit $?

