#!/bin/sh

echo "LD Wrapping $@"

LD_CMD=mslink
case $VLC_PLATFORM in
	Windows|Metrox86)
		FORCED_LIBS="mincore.lib"
#		FORCED_LIBS="user32.lib kernel32.lib Advapi32.lib Ole32.lib RuntimeObject.lib -NODEFAULTLIB:ole32.lib -NODEFAULTLIB:kernel32.lib -NODEFAULTLIB:ws2_32.lib"
		;;
	WindowsPhone)
		FORCED_LIBS="mincore.lib"
#		FORCED_LIBS="-APPCONTAINER WindowsPhoneCore.lib RuntimeObject.lib PhoneAppModelHost.lib -NODEFAULTLIB:ole32.lib -NODEFAULTLIB:kernel32.lib -NODEFAULTLIB:ws2_32.lib"
		;;
	*)
		echo "clwrap: Invalid platform: $VLC_PLATFORM"
		exit 1
esac

if [ "$VLC_CONFIGURATION" == "Debug" ]; then
#  FORCED_LIBS="$FORCED_LIBS -NODEFAULTLIB:msvcrt.lib -NODEFAULTLIB:libcmt.lib"
else
#  FORCED_LIBS="$FORCED_LIBS -NODEFAULTLIB:msvcrtd.lib -NODEFAULTLIB:libcmtd.lib"
fi

while [ $# -gt 0 ]; do
    case $1 in
        /[a-z]/*)
            param=`cygpath -w $1`
            ;;
        /*)
            param=-"${1#/}"
            ;;
        *)
            param=$1
            ;;
    esac
	case $param in
	-out:*)
		LINK_TARGET=${param#-out:}
		shift
		;;
	-o)
		LINK_TARGET=`cygpath -w $2`
		shift
		;;
	*.o)
		if [ -f $param ]; then
			OBJS="$OBJS `cygpath -w $param`"
		else
			# Manually fix the extension if the object file doesn't exist
			OBJS="$OBJS `cygpath -w $param`"bj
		fi
		
		;;
	*.obj)
		OBJS="$OBJS `cygpath -w $param`"
		;;
	-implib:*)
		ARGS="$ARGS $param"
		;;
	-l*)
		OBJS="$OBJS ${param#-l}.lib"
		;;
	*.lib)
		OBJS="$OBJS $param"
		;;
	-L*)
		libpath=${param#-L}
		if [ "$libpath" != "/mingw32/lib" ]; then
			LIBDIR="$LIBDIR -LIBPATH:`cygpath -w $libpath`"
		fi
		;;
	-pdb:*)
		#TODO ARGS="$ARGS -pdb:`cygpath -w $param`"
		;;
	-MANIFEST*)
		# not working yet
		;;
	-r)
		LD_CMD=lib
		#FORCED_LIBS=
		;;
	-*)
		ARGS="$ARGS $param"
		;;
	*)
#		echo "Ignoring AR flag: $param"
		ARGS="$ARGS $param"
		;;
	esac
	shift
done

if [ "$LINK_TARGET" = "" ]; then
	echo "Failed to extract target"
	exit 1
fi

echo "LD: $LD_CMD"
echo "Args: $ARGS"
echo "Objs: $OBJS"

#MSVCRTDIR="-LIBPATH:`cygpath -w '/c/Program Files (x86)/Microsoft Visual Studio 11.0/VC/WPSDK/WP80/lib/arm'`"
#echo $LD_CMD -nologo -OPT:REF -OUT:$LINK_TARGET $ARGS $OBJS $LIBDIR $FORCED_LIBS
$LD_CMD -nologo -OPT:REF -OUT:$LINK_TARGET $ARGS $OBJS $LIBDIR $FORCED_LIBS # -NODEFAULTLIB:msvcrt msvcrt.lib $MSVCRTDIR
exit $?

