#!/bin/sh

# link.exe is both MSVC's linker and a part of GNU's coreutil.
# In order for FFMPEG to build properly, it needs to detect 
# link as part of MS toolchain.
# This wrapper scripts removes link from the path before running it

SED=`which sed`
# We know the first element in $PATH is our wrapper script, 
# so /usr/bin & /bin won't be the first item
export PATH="`echo $PATH | $SED 's/\:\/usr\/bin//'`"
export PATH="`echo $PATH | $SED 's/\:\/bin//'`"
link.exe $@
exit $?