#!/bin/sh

echo "Wrapping windres $@"

#windres --include-dir ../../share --include-dir ../../extras/package/win32 -i libvlc_win32_rc.rc -o libvlc_win32_rc.obj

while [ $# -gt 0 ]; do
    case $1 in 
        --include-dir)
            ARGS="$ARGS -I $(wslpath -m $2)"
            shift
            ;;
        --include-dir=*)
            ARGS="$ARGS -I $(wslpath -m ${1#--include-dir=})"
            ;;
        -i)
            INPUT=$(wslpath -m $2)
            shift
            ;;
        -o)
            ARGS="$ARGS -fo $(wslpath -m $2)"
            shift
            ;;
        -D*)
            def=$(echo $1 | sed 's/\\\"/\"/g')
            ARGS="$ARGS $def"
            ;;
        *)
            if [ "$INPUT" = "" ]; then
                INPUT=$(wslpath -m $1)
            else
                echo "Unknown option $1"
            fi
            ;;
    esac
    shift
done

echo "Args: $ARGS"
echo "Input: $INPUT"
#~ echo "PATH: $PATH"

echo rc.exe $ARGS $INPUT
cmd.exe /C rc.exe $ARGS $INPUT
exit $?
